name: running cron job

on:
  schedule:
    - cron: '0 20 * * 1,4'

jobs:
  test_scheduler:
    runs-on: ubuntu-latest
    steps:
      - name: Not on monday or thursday
        if: github.event.schedule == '0 20 * * 1,4'
        run: echo "This step will run on Monday and thursday"
      - name: Every Time
        run: echo "This step will run always"