name: 03-Workflow Runners

on: push

jobs:
    ubuntu-echo:
        runs-on: ubuntu-latest
        steps:
            - name: Show OS
              run: |
                echo "This job is running in a ubuntu runner"
                echo "Runner OS: $RUNNER_OS"
    
    widnows-echo:
        runs-on: windows-latest
        steps:
            - name: Show OS
              run: |
                echo "This job is running in on a windows runner"
                echo "Runner OS: $RUNNER_OS"