name: 09 - Using Functions

on: 
    pull_request:
    workflow_dispatch:

jobs:
    echo1:
        runs-on: ubuntu-latest
        steps:
            - name: Failing Step
              run: exit 1
            - name: This will be skipped
              if: ${{ success() }}
              run: echo "i will print if previous step succed."
            - name: I will execute
              if: ${{ failure() }}
              run: echo "i will print if any previous step failed"
            - name: i will execute
              if: ${{ !cancelled() }}
              run: echo "i will always print unless the workflow was cancelled"
            - name: i will execute
              if: ${{ cancelled() }}
              run: echo "i will print if the workflow was cancelled"