name: 13 - Using Caching

on:
  workflow_dispatch:
    inputs:
      use-cache:
        description: Whether to execute cache step
        type: boolean
        default: true
      node-version:
        description: Node Version
        type: choice
        options:
            - '18.x'
            - '20.x'
            - '22.x'
        default: '20.x'

jobs:
  caching:
    runs-on: ubuntu-latest
    defaults:
        run:
            working-directory: ./13-caching
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
            node-version: ${{ inputs.node-version }}
      - name: Install Dependencies
        run: npm ci

      - name: Test
        run: npm test

      - name: Building
        run: npm run build

      - name: Deploy to nonProd
        run: echo "Deploying to non prod environment"
    
      
        