name: Workflow commands

on: 
  - push
  - workflow_dispatch


jobs:
  testing-wf-commnads:
    runs-on: ubuntu-latest
    steps:
      - name: Setting an error mesage
        run: echo "::error::Missing semicolon"